# Generated by Django 2.0.3 on 2020-03-23 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CpuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='avatar')),
                ('mark', models.IntegerField()),
                ('category', models.IntegerField(choices=[(0, 'AMD'), (1, 'Intel')])),
                ('price', models.IntegerField()),
                ('purpose', models.IntegerField(choices=[(0, 'Entertainment'), (1, 'office'), (2, 'Gaming and professional production')])),
                ('core', models.IntegerField(choices=[(0, 'four core'), (1, 'six core'), (2, 'eight core'), (4, 'ten core')])),
                ('frequency', models.FloatField()),
                ('label', models.CharField(default='i3', max_length=100)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='avatar')),
                ('content', models.TextField(verbose_name='content')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_list', to='CPUNerd.CpuModel', verbose_name='cpu'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
