# Generated by Django 2.0 on 2020-03-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='avatar')),
                ('mark', models.IntegerField()),
                ('category', models.IntegerField(choices=[(0, 'AMD'), (1, 'Intel')])),
                ('price', models.IntegerField()),
                ('purpose', models.IntegerField(choices=[(0, 'Entertainment'), (1, 'office'), (2, 'Gaming and professional production')])),
                ('core', models.IntegerField(choices=[(0, 'four hz'), (1, 'six hz'), (2, 'eight hx'), (4, 'ten hx')])),
                ('frequency', models.FloatField()),
            ],
        ),
    ]
