# Generated by Django 2.0.3 on 2020-03-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPUNerd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpumodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
