# Generated by Django 2.0.3 on 2020-03-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPUNerd', '0003_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpumodel',
            name='label',
            field=models.CharField(default='i3', max_length=100),
        ),
        migrations.AlterField(
            model_name='cpumodel',
            name='core',
            field=models.IntegerField(choices=[(0, 'four core'), (1, 'six core'), (2, 'eight core'), (4, 'ten core')]),
        ),
    ]
