# Generated by Django 2.0.3 on 2020-03-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPUNerd', '0005_newsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpumodel',
            name='indexIMG',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='avatar'),
        ),
    ]
